services:
  web:
    build: .
    image: aprotech-docs/app:latest
    container_name: aprotech-docs
    restart: always
    env_file:
      - .env.production
    volumes:
      - .:/code
    ports:
      - "3006:3000"
